const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function addTestAlert() {
    const users = await prisma.user.findMany();

    if (users.length === 0) {
        console.log("No users found to attach the alert to. Please create a user first via the Register screen.");
        return;
    }

    const targetUser = users[0];

    await prisma.alert.create({
        data: {
            userId: targetUser.id,
            title: 'Welcome to the New Database!',
            message: 'Your system has successfully migrated to UUID support and all alerts are now dynamically generated by the backend API.',
            type: 'info'
        }
    });

    await prisma.alert.create({
        data: {
            userId: targetUser.id,
            title: 'Vehicle Inspection Reminder',
            message: 'Your car RAB 123A is due for inspection in 25 days. Please schedule an appointment.',
            type: 'warning'
        }
    });

    console.log(`Successfully added 2 Test Alerts to user: ${targetUser.email}`);
}

addTestAlert().catch(e => console.error(e)).finally(() => prisma.$disconnect());
